select * from customer limit 10;

--1. What is total revenue generated by male vs.female customers?
SELECT gender, sum(purchase_amount) as revenue
FROM customer
GROUP BY gender;

--2. Which customers used a discount still spent more than average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount>= (SELECT avg(purchase_amount) FROM customer);

--3. WHich are top 5 products with highest average review rating?
SELECT item_purchased, round(AVG(review_rating::numeric),2) AS avg_review
FROM customer
GROUP BY item_purchased
ORDER BY avg_review desc LIMIT 5;

--4. Compare avg purchase amounts between standard and express shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subs..
SELECT Subscription_status ,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY Subscription_status
ORDER BY total_revenue, avg_spend DESC;

--6. Which 5 products have highest % of purchases with discounts applied? 
SELECT item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' 
		 		THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC LIMIT 5;

--7. Segment customers into new, returning and loyal based on their total
--number of previous purchases, and show count of each segment.
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New'
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "number of customers"
FROM customer_type
GROUP BY customer_segment;

--8. What are top 3 most purchased products within each category?
WITH item_counts AS(
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC ) AS item_rank
FROM customer 
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--10. What is revenue contribution of each age group?
SELECT age_group, sum(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC ;
